### ISSUE TITLE
robpca should return a pca-like object, with a class, not a list

### ISSUE THREAD

**Issue by friendly** [TReynkens/rospca#1]
Hi
I'd like to be able to try `robpca` with my `ggbiplot` package, but I can't because it just returns a list with named components, not an object with a recognizable class I can work with.

Are you still maintaining this package? If so, that would be a welcome addition.

**Comment by TReynkens** [comment]
Hi,
Thank you for the interest in the `rospca` package. The package is still maintained in the sense that bugs are fixed.
Major changes such as changing the output format are currently not done.

Kind regards,

Tom
